---
swagger: "2.0"
info:
  description: "This is the API for the backend server (orchestrator) of the US Post\
    \ prototype for the ACIT Cloud Studio"
  version: "1.0.0"
  title: "Swagger USPS"
  termsOfService: "http://swagger.io/terms/"
  contact:
    email: "thomas.i.jacobs@accenture.com"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "postal-scm-go-dev.mybluemix.net"
basePath: "/"
tags:
- name: "Input Data"
  description: "submit the EDI data into the environment."
schemes:
- "http"
paths:
  /input-data:
    post:
      tags:
      - "Input Data"
      summary: "Uplaod Data from EDI message"
      description: "This endpoint will take the package Data from EDI message"
      operationId: "inputData"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        description: "EDI Data"
        required: true
        schema:
          $ref: "#/definitions/inputData"
      responses:
        200:
          description: "OK"
        405:
          description: "Was not able to get simulated data"
definitions:
  inputData:
    type: "object"
    properties:
      origin:
        type: "string"
      destination:
        type: "string"
      dispatchId:
        type: "string"
      packageId:
        type: "string"
      receptacleId:
        type: "string"
      weight:
        type: "string"
      shipmentStatus:
        type: "string"
